// TABELAS

Table Custos {
  ID_Custo integer [primary key]
  ID_Chamado integer [ref: - Chamados.ID_Chamado, not null]
  Custo numeric
}

Table Clientes {
  ID_Cliente integer [primary key]
  Nome varchar
  Email varchar
  Região varchar
  Idade integer
}

Table Atendentes {
  ID_Atendente integer [primary key]
  Nome_Atendente varchar
  Nivel_Atendimento integer
}

Table Motivos {
  ID_Motivo integer [primary key]
  Nome_Motivo varchar
  Categoria varchar
  Criticidade varchar
}

Table Pesquisas_Satisfacao {
  ID_Pesquisa integer [primary key]
  ID_Chamado integer [ref: - Chamados.ID_Chamado, not null]
  Nota_Atendimento integer
}

Table Canais {
  Nome_Canal varchar
  Status_Canal varchar
}

Table Chamados_Hora { 
  ID_Chamado integer [primary key, ref: - Chamados.ID_Chamado, not null]
  ID_Cliente integer 
  Hora_Abertura_Chamado timestamp
  Hora_Inicio_Atendimento timestamp
  Hora_Finalizacao_Atendimento timestamp
}

Table Chamados {
  ID_Chamado integer [primary key]
  ID_Cliente integer
  Motivo varchar
  Canal varchar
  Resolvido bool
  Hora_Abertura_Chamado timestamp
  Hora_Inicio_Atendimento timestamp
  Hora_Finalizacao_Atendimento timestamp
  Tempo_Espera integer
  Tempo_Atendimento integer
  ID_Atendente integer
}


// RELAÇÕES

// Chamados <-> Clientes
Ref: Chamados.ID_Cliente > Clientes.ID_Cliente

// Chamados <-> Atendentes
Ref: Chamados.ID_Atendente > Atendentes.ID_Atendente

// Chamados <-> Motivos
Ref: Chamados.Motivo > Motivos.Nome_Motivo

// Chamados <-> Canais
Ref: Chamados.Canal > Canais.Nome_Canal