// TABELAS

Table silver_dim_custos {
  id_custo integer [primary key]
  id_chamado int [ref: - silver_fato_chamados.id_chamado, not null] // Relação 1:1
  valor_custo decimal(18,10)
  bronze_ingestion_timestamp timestamp
  silver_ingestion_timestamp timestamp
}

Table silver_dim_clientes {
  id_cliente integer [primary key]
  nome string
  email string
  regiao string
  idade int
  faixa_etaria_geracao string
  flag_idoso int
  bronze_ingestion_timestamp timestamp
  silver_ingestion_timestamp timestamp
}

Table silver_dim_atendentes {
  id_atendente integer [primary key,  ref: - silver_fato_chamados.id_atendente, not null] // Relação 1:1
  nome_atendente varchar
  nivel_atendimento integer
  descricao_nivel varchar 
  bronze_ingestion_timestamp timestamp
  silver_ingestion_timestamp timestamp
}

Table silver_dim_motivos {
  id_motivo integer [primary key]
  nome_motivo string
  categoria_motivo string
  criticidade_motivo string
  bronze_ingestion_timestamp timestamp
  nome_motivo_clean string
  silver_ingestion_timestamp timestamp
}

Table silver_dim_pesquisas_satisfacao {
  id_pesquisa integer [primary key]
  id_chamado integer [ref: - silver_fato_chamados.id_chamado, not null] // Relação 1:1
  nota_atendimento int
  bronze_ingestion_timestamp timestamp
  silver_ingestion_timestamp timestamp
}

Table silver_dim_canais {
  nome_canal varchar
  status_canal varchar
  bronze_ingestion_timestamp timestamp
  silver_ingestion_timestamp timestamp
}

Table silver_dim_chamados_data { 
  id_chamado bigint [primary key, ref: - silver_fato_chamados.id_chamado, not null] // Relação 1:1
  id_cliente bigint
  data_hora_abertura timestamp
  data_hora_inicio_atendimento timestamp
  data_hora_finalizacao_atendimento timestamp
  tempo_espera_atendimento_min double
  tempo_atendimento_min double
  ano integer
  mes integer
  dia integer
  dia_semana_num int
  nome_dia string
  trimestre int
  semana_do_ano int
  flag_fim_de_semana boolean
  ciclo_operacional string
  evento_sazonal string
  bronze_ingestion_timestamp timestamp
  silver_ingestion_timestamp  timestamp
}

Table silver_fato_chamados {
  id_chamado bigint [primary key]
  id_atendente bigint
  id_cliente bigint
  nome_motivo_clean string
  resolvido boolean
  nome_canal string
  bronze_ingestion_timestamp timestamp
  silver_ingestion_timestamp  timestamp
}


// RELAÇÕES 1:N

// Chamados <-> Clientes
Ref: silver_fato_chamados.id_cliente > silver_dim_clientes.id_cliente

// Chamados <-> Motivos
Ref: silver_fato_chamados.nome_motivo_clean > silver_dim_motivos.nome_motivo_clean

// Chamados <-> Canais
Ref: silver_fato_chamados.nome_canal > silver_dim_canais.nome_canal